blog/urls.py
from . import views
from django.urls import path
from .views import DeleteRecipeView, UpdateRecipeView

urlpatterns = [
    path("", views.RecipeModelList.as_view(), name="home"),
    path('about/', views.about, name='about'),
    path('detail/<slug:slug>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('like/<slug:slug>', views.RecipeLike.as_view(), name='recipe_like'),
    path('addrecipe/', views.add_recipe, name='addrecipe'),
    path('recipe_edit/<slug:slug>', views.UpdateRecipeView.as_view(),
         name='recipe_edit'),
    path('recipe_delete/<slug:slug>', views.DeleteRecipeView.as_view(),
         name='recipe_delete'),
]

eatopia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.template.defaultfilters import slugify
from django_summernote.fields import SummernoteTextField
from cloudinary.models import CloudinaryField

STATUS = ((0, 'Draft'), (1, 'Published'))


class RecipeModel(models.Model):
    """
    Model for recipe
    """

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipe_author')
    updated_on = models.DateTimeField(auto_now=True)
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    cooking_time = models.IntegerField(default=1,
                                       validators=[
                                                   MinValueValidator(1),
                                                   MaxValueValidator(120)
                                                   ])
    ingredients_list = SummernoteTextField()
    instructions = SummernoteTextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='recipe_likes',
                                   blank=True)

    class Meta:
        """
        Order the recipes in descending order
        """
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        """
        Returns the number of likes on a post
        """
        return self.likes.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Comment(models.Model):
    """
    Model for comment
    """
    recipe = models.ForeignKey(RecipeModel, on_delete=models.CASCADE,
                              related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_comments')
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.author}"

blog/forms.py
from .models import Comment, RecipeModel
from django import forms


class AddRecipeForm(forms.ModelForm):
    """
    Form to add recipe
    """
    class Meta:
        model = RecipeModel
        fields = [
            'title',
            'excerpt',
            'cooking_time',
            'ingredients_list',
            'instructions',
            'featured_image',
        ]

    def __init__(self, *args, **kwargs):
        super(AddRecipeForm, self).__init__(*args, **kwargs)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import redirect, render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, DeleteView
from .models import RecipeModel
from .forms import CommentForm
from .forms import AddRecipeForm


class RecipeModelList(generic.ListView):
    model = RecipeModel
    queryset = RecipeModel.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 6


class RecipeDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = RecipeModel.objects.filter(status=1)
        recipemodel = get_object_or_404(queryset, slug=slug)
        comments = recipemodel.comments.order_by("-created_on")
        liked = False
        if recipemodel.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "recipe_detail.html",
            {
                "recipemodel": recipemodel,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm(),
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = RecipeModel.objects.filter(status=1)
        recipemodel = get_object_or_404(queryset, slug=slug)
        comments = recipemodel.comments.order_by("-created_on")
        liked = False
        if recipemodel.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.recipe = recipemodel
            comment.author = request.user
            comment.save()

        else:
            comment_form = CommentForm()

        return render(
            request,
            "recipe_detail.html",
            {
                "recipemodel": recipemodel,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm(),
            },
        )


@login_required
def add_recipe(request):
    """
    Add recipe page
    """
    recipe_form = AddRecipeForm()
    print(request.method)
    if request.method == "POST":
        recipe_form = AddRecipeForm(request.POST, request.FILES)
        print(recipe_form.is_valid())
        if recipe_form.is_valid():
            recipe_form = recipe_form.save(commit=False)
            recipe_form.title = recipe_form.title.title()
            recipe_form.author = request.user
            recipe_form.status = 1
            recipe_form.save()
            return redirect('home')

    return render(request, 'add_recipe.html', context={'recipe_form':
                  recipe_form})


class RecipeLike(View):
    """
    Likes
    """
    def post(self, request, slug, *args, **kwargs):
        recipemodel = get_object_or_404(RecipeModel, slug=slug)

        if recipemodel.likes.filter(id=request.user.id).exists():
            recipemodel.likes.remove(request.user)
        else:
            recipemodel.likes.add(request.user)

        return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


class UpdateRecipeView(UpdateView):
    """
    Edit recipe
    """
    model = RecipeModel
    form_class = AddRecipeForm
    template_name_suffix = '_update_form'
    template_name = 'update_recipe.html'
    success_url = '/'


class DeleteRecipeView(DeleteView):
    """
    Delete Recipe
    """
    model = RecipeModel
    template_name = 'delete_recipe.html'
    success_url = reverse_lazy('home')


def about(request):
    """
    Renders about page
    """
    return render(request, 'about.html')

templates/about.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row text-center mt-3">
        <h1>Welcome to Eatopia</h1>
        <p>Welcome to Eatopia, where, you guessed it! We are creating a Utopia for all Foodies<br>
            Tasty meals for any budget, flavoursome dishes for all the family to enjoy! </p>
    </div>
    <div class="row mt-3 about-taste">
        <div class="col-6 text-center d-none d-md-block">
            <img class="about-image"
                src="https://res.cloudinary.com/dvfyeucsp/image/upload/v1677068373/satay_dq5zfa.jpg"
                alt="Satay Chicken">
        </div>
        <div class="col-md-6">
            <h4>All About Taste</h4>
            <p>The first thing any of us think about when we are deciding what to eat is the taste,
                well here at Eatopia, we have made the decision a heck of a lot easier for you by providing 
                a platform for everyone to share their tastiest recipes, there's sureto be  something that will catch your eye,
                flavour is important, and here, flavour is evrything.
            </p>
        </div>
    </div>
    <div class="row mt-3 about-taste">
        <div class="col-6 text-center d-none d-md-block">
            <img class="about-image"
                src="https://res.cloudinary.com/dvfyeucsp/image/upload/v1677068381/pie_jkbys5.jpg"
                alt="Budget pie">
        </div>
        <div class="col-md-6">
            <h4>Budget Friendly</h4>
            <p>
                Of course we all love a tasty meal, but sometimes those fancy recipes can be a little harsh on the pocket,
                but what if there was a way to eat high end meals without breaking the bank, well now there is, the recipes 
                on Eatopia are budget and belly friendly!! Whether you're dining alone or feeding a family, our recipes will cater
                to all your needs. 
            </p>
        </div>
    </div>
</div>

{% endblock %}

templates/add_recipe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}

{% block content %}

{% if user.is_authenticated %}
<div class="container">
    <h1>Add a delicious recipe!!</h1>
    <div class="row">
        <div class="col mt-3 mb-5">
            <form action="{% url 'addrecipe' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        {{ recipe_form.title|as_crispy_field }}
                    </div>
                    <div class="col-6">
                        {{ recipe_form.cooking_time|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        {{ recipe_form.excerpt|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    {{ recipe_form.ingredients_list|as_crispy_field|safe }}
                </div>
                <div class="row">
                    {{ recipe_form.instructions|as_crispy_field|safe }}
                </div>
                <div class="row">
                    {{ recipe_form.featured_image|as_crispy_field }}
                    <p>If no image is uploaded a default image will be displayed</p>
                </div>
                <button type="submit" class="add-recipe-button">Submit</button>
            </form>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <p>Please <a href="{% url 'account_signup' %}"> Sign up or <a href="{% url 'account_login' %}"> Login to share a
                recipe!</a></p>
</div>
{% endif %}

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">



<head>
    <title>Eatopia</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="https://res.cloudinary.com/dvfyeucsp/image/upload/v1676301968/Screenshot_1_ashlbo.png"
                    alt="eatopia-logo" style="width:140px; height: 140px;">

            </a>
            
                <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'addrecipe' %}">Add Recipe</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    A Foodie's guide to Eatopia
                </span>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Eatopia</p>
        <p class="m-0 text-center text-white">Follow us:
            <a href="https://www.facebook.com" target="_blank" rel="noopener"
                aria-label="Visit our Facebook page (opens in new tab)"><i class="fab fa-facebook-square ms-3"></i></a>
            <a href="https://www.twitter.com" target="_blank" rel="noopener"
                aria-label="Visit our twitter page (opens in new tab)"><i class="fab fa-twitter-square ms-3"></i></a>
            <a href="https://www.instagram.com" target="_blank" rel="noopener"
                aria-label="Visit our instagram page (opens in new tab)"><i class="fab fa-instagram-square ms-3"></i>
                <a href="https://www.youtube.com" target="_blank" rel="noopener"
                    aria-label="Visit our youtube page (opens in new tab)"><i class="fab fa-youtube-square ms-3"></i>
        </p>
    </footer>

    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>
</body>

</html>

templates/delete_recipe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}


{% block content %}

<div class="container">
    {% if request.user == recipemodel.author %}
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'recipe_detail' recipemodel.slug %}" class="btn btn-light">Back to Eatopia</a>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5 col-sm-12">
            <h5>Are You Sure?</h5>
            <p>You are about to delete this post, this cannot be undone.</p>
        <form method="POST">
            {% csrf_token %}
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
        </div>
    </div>
    {% else %}
    <p>You are not authorized to visit this page.</p>
    <div class="container text-center">
        <a href="{% url 'home' %}" class="back-button btn-default">Back</a>
    </div>
    {% endif %}
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid callout-container">
    <div class="row">
        <div class="col-12">
            <section class="callout jumbotron text-center">
                <h1>Eatopia!</h1>
                <p>A Utopia for all Foodies to share their recipes!</p>
            </section>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            {% if user.is_authenticated %}
            <h2>Welcome {{ user.username }}!</h2>
            <p>Let's explore Eatopia!<br>Share your own recipes, comment other recipes and explore 
            the wonderful world of food!</p>
            {% else %}
            <h2>Welcome to Eatopia</h2>
            <h3>To share your own recipes, please <a href="{% url 'account_login' %}">
                    Login</a> or <a href="{% url 'account_signup' %}">Register</a> to create an account!</h3>
            {% endif %}
        </div>

        <!-- Recipe Entries Column -->
        <div class="col-12 mt-3 left recipe-list">
            <div class="row mb-3">
            {% for recipemodel in recipemodel_list %}
                <div class="col-md-4">
                    <div class="card-sm-4">
                        <div class="card card-body text-center h-100">
                            <div class="image-container">
                                {% if "placeholder" in recipemodel.featured_image.url %}
                                <img class="card-img-top"
                                    src=https://res.cloudinary.com/dvfyeucsp/image/upload/v1675266749/cld-sample-4.jpg>
                                {% else %}
                                <img class="card-img-top" src=" {{ recipemodel.featured_image.url }}" alt="{{ recipemodel.slug }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ recipemodel.author }}</p>
                                </div>
                            </div>
                           
                            <a href="{% url 'recipe_detail' recipemodel.slug %}" class="post-link">
                                <h2>{{ recipemodel.title }}</h2>
                                <p>{{ recipemodel.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ recipemodel.created_on}} <i class="far fa-heart"></i>
                                {{ recipemodel.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
        

            {% if forloop.counter|divisibleby:3 %}
            </div> 
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}

</div>

{%endblock%}

templates/recipe_detail.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}



<div class="container mt-4">

    <!-- Recipe details -->
    <div class="row">
        <div class="col-4">
            {% if "placeholder" in recipemodel.featured_image.url %}
            <img class="card-img-top"
                src="https://res.cloudinary.com/dvfyeucsp/image/upload/v1675266749/cld-sample-4.jpg" alt="Tasty Recipe">
            {% else %}
            <img class="card-img-top" src="{{ recipemodel.featured_image.url }}" alt="Tasty Recipe">
            {% endif %}
        </div>
        <div class="col-6">
            <h1>{{ recipemodel.title }}</h1>
            <p>{{ recipemodel.excerpt }}</p>
            <p>{{ recipemodel.author }} | {{ recipemodel.updated_on}}</p>
            <p>Cooking time: {{ recipemodel.cooking_time }} min</p>
        </div>
    </div>
    <div class="row">
        <h5>Ingredients:</h5>
        <div class="col">{{ recipemodel.ingredients_list | safe }}</div>
    </div>
    <div class="row">
        <h5>Instructions:</h5>
        <div class="col">{{ recipemodel.instructions | safe }}</div>
    </div>
    <div class="row">
        <div class="col">
            <p class="card-text text-muted h6">{{ recipemodel.created_on}}</p>
        </div>
    </div>
    <hr class="block-divider">

    <div class="row">
        <div class="col-1">
            <strong>
                {% if user.is_authenticated %}
                <form class="d-inline" action="{% url 'recipe_like' recipemodel.slug %}" method="POST">
                    {% csrf_token %}
                    {% if liked %}
                    <button type="submit" name="recipe_id" value="{{ recipemodel.slug }}" class="btn btn-md"><i
                            class="fas fa-heart"></i>
                        {{ recipe.amount_of_likes }} </button>
                    {% else %}
                    <button type="submit" name="recipe_id" value="{{ recipemodel.slug }}" class="btn btn-md"><i
                            class="far fa-heart"></i>
                        {{ recipemodel.amount_of_likes }}</button>

                    {% endif %}
                </form>
                {% else %}
                <span class="text-secondary"><i class="fas fa-heart"></i></span>
                {% endif %}
                <span class="text-secondary">{{ recipemodel.number_of_likes }}</span>
            </strong>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        
                        {{ comment.author }}
                        <span class=" text-muted font-weight-normal">
                            
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    
                    {{ comment.body | linebreaks }}
                </div>
                
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                
                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <div class="row">
            <div class="col-6">
                {% if request.user == recipemodel.author %}
                <h5>Manage your recipe:</h5>
                <strong>{{ recipemodel.author }}</strong> - {{ recipemodel.title }}
                <p class="edit-delete"><a href="{% url 'recipe_edit' recipemodel.slug %}"><button
                            class="btn btn-success edit-recipe"><i class="fa fa-edit"></i> | Edit</button></i></a>
                    <a href="{% url 'recipe_delete' recipemodel.slug %}"><button class="btn btn-danger"><i
                                class="fa fa-trash"></i> | Delete</button></a></p>
                {% endif %}
            </div>
        </div>
    </div>

<div class="container text-center">
    <br /><br />
    <a href="{% url 'home' %}" class="back back-button page-link btn-default">Back</a>
</div>

{% endblock content %}

templates/update_recipe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}


{% block content %}

<div class="container">
    {% if request.user == recipemodel.author %}
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'recipe_detail' recipemodel.slug %}" class="btn btn-light">Back to Feed</a>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5 col-sm-12">
            <h5>Update Your Recipe</h5>
        </div>
    </div>
    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <input type="submit" class="btn btn-success mt-3" value="Submit">
                </div>
            </form>
        </div>
    </div>
    {% else %}
    <p>You are not authorized to visit this page.</p>
    <div class="container text-center">
        <a href="{% url 'home' %}" class="back-button btn-default">Back</a>
    </div>
    {% endif %}
</div>

{% endblock %}